// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8BHzW5yiZ5BSYRfTkMbvbs8CGBkWkAm8',
    appId: '1:178121884772:web:7d89150076b29f5dc3cb71',
    messagingSenderId: '178121884772',
    projectId: 'stockiteasy-9debf',
    authDomain: 'stockiteasy-9debf.firebaseapp.com',
    storageBucket: 'stockiteasy-9debf.appspot.com',
    measurementId: 'G-7NJL8ENF9B',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8BHzW5yiZ5BSYRfTkMbvbs8CGBkWkAm8',
    appId: '1:178121884772:web:7d89150076b29f5dc3cb71',
    messagingSenderId: '178121884772',
    projectId: 'stockiteasy-9debf',
    authDomain: 'stockiteasy-9debf.firebaseapp.com',
    storageBucket: 'stockiteasy-9debf.appspot.com',
    measurementId: 'G-7NJL8ENF9B',
  );
}