// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA91RSuXaLpOrUtNatnYSpGcepAf6GNuPI',
    appId: '1:178121884772:web:f5b872427dd00280c3cb71',
    messagingSenderId: '178121884772',
    projectId: 'stockiteasy-9debf',
    authDomain: 'stockiteasy-9debf.firebaseapp.com',
    storageBucket: 'stockiteasy-9debf.appspot.com',
    measurementId: 'G-1Q9CVZVTE5',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8BHzW5yiZ5BSYRfTkMbvbs8CGBkWkAm8',
    appId: '1:178121884772:web:7d89150076b29f5dc3cb71',
    messagingSenderId: '178121884772',
    projectId: 'stockiteasy-9debf',
    authDomain: 'stockiteasy-9debf.firebaseapp.com',
    storageBucket: 'stockiteasy-9debf.appspot.com',
    measurementId: 'G-7NJL8ENF9B',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwo_dARChoqyRs15FgdOs-_JY6BwBgVZ4',
    appId: '1:178121884772:ios:e4a292cc01d9d7f9c3cb71',
    messagingSenderId: '178121884772',
    projectId: 'stockiteasy-9debf',
    storageBucket: 'stockiteasy-9debf.appspot.com',
    androidClientId: '178121884772-kbksiqsgb4teev4tq4u8aemvhjg68b90.apps.googleusercontent.com',
    iosClientId: '178121884772-cn6c5rq6aiq9u7stvksliaiku1bjvvhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockflow',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwo_dARChoqyRs15FgdOs-_JY6BwBgVZ4',
    appId: '1:178121884772:ios:e4a292cc01d9d7f9c3cb71',
    messagingSenderId: '178121884772',
    projectId: 'stockiteasy-9debf',
    storageBucket: 'stockiteasy-9debf.appspot.com',
    androidClientId: '178121884772-kbksiqsgb4teev4tq4u8aemvhjg68b90.apps.googleusercontent.com',
    iosClientId: '178121884772-cn6c5rq6aiq9u7stvksliaiku1bjvvhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockflow',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmllgRZi07eIXPmIeZXwV_2--4cLS_YCw',
    appId: '1:178121884772:android:d0f55a9682a1b63dc3cb71',
    messagingSenderId: '178121884772',
    projectId: 'stockiteasy-9debf',
    storageBucket: 'stockiteasy-9debf.appspot.com',
  );

}